name: Python package
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'    # excludes main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup just
        uses: extractions/setup-just@v1
      - uses: sparksp/elm-format-action@v1
        with:
            elm_files: |
              elm/src/
      - name: Compile Elm
        run: just check
