name: Python package
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'    # excludes main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup just
        uses: extractions/setup-just@v1
      - uses: actions/setup-node@v3
        with:
            # Node needed for elm-format
            node-version: 18
      - name: elm-format install
        run: npm elm-format install
      - name: Compile Elm
        run: just check
